#!/bin/bash

rm -f ~/.zshrc
rm -f ~/.vimrc

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

echo "export CONFDIR=$SCRIPTPATH/zsh" > ~/.zshrc
cat $SCRIPTPATH/zsh/conf >> ~/.zshrc
ln -s $SCRIPTPATH/vimrc ~/.vimrc
git submodule update --init --recursive

